name: Ralph Loop

on:
  issues:
    types: [labeled]
  pull_request:
    types: [labeled]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  reject-pr:
    if: github.event_name == 'pull_request' && github.event.label.name == 'ralph'
    runs-on: ubuntu-latest
    steps:
      - name: Comment on PR
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          existing="$(gh pr view "${{ github.event.pull_request.number }}" \
            --repo "${{ github.repository }}" \
            --json comments --jq '.comments[].body' \
            | grep -c '🤖 \*\*Ralph\*\*' || true)"
          if [[ "${existing}" -eq 0 ]]; then
            gh pr comment "${{ github.event.pull_request.number }}" \
              --repo "${{ github.repository }}" \
              --body "🤖 **Ralph** can only work on issues, not pull requests. Please create an issue and label it with \`ralph\` instead."
          fi

  ralph:
    if: github.event_name == 'issues' && github.event.label.name == 'ralph'
    runs-on: ubuntu-latest
    timeout-minutes: 60
    concurrency:
      group: ralph-${{ github.event.issue.number }}
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v4

      - uses: mdelapenya/claude-ralph-github-action@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          # Optional: customize models
          # worker_model: 'opus'
          # reviewer_model: 'sonnet'
          # Optional: adjust iteration limits
          # max_iterations: 5
          # max_turns_worker: 30
          # max_turns_reviewer: 30
          # Optional: change trigger label
          # trigger_label: 'ralph'
          # Optional: change base branch
          # base_branch: 'main'
