#!/usr/bin/env bash
# pr-manager.sh - PR creation/update and issue commenting
#
# Functions for managing the pull request and issue comments
# associated with a Ralph loop run.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/state.sh"

REPO="${GITHUB_REPOSITORY}"

# Create or update a pull request for the Ralph branch.
# Args: $1 = branch name, $2 = base branch, $3 = issue number,
#       $4 = issue title, $5 = final status
# Outputs: PR URL to stdout
pr_create_or_update() {
  local branch="$1"
  local base_branch="$2"
  local issue_number="$3"
  local issue_title="$4"
  local final_status="$5"

  local iteration
  iteration="$(state_read_iteration)"
  local work_summary
  work_summary="$(state_read_work_summary)"
  local review_feedback
  review_feedback="$(state_read_review_feedback)"

  # Use the reviewer's PR title if available, otherwise fall back to issue title
  local pr_title
  if [[ -f ".ralph/pr-title.txt" ]]; then
    pr_title="$(cat .ralph/pr-title.txt)"
  else
    pr_title="feat: ${issue_title}"
  fi

  # Build PR body
  local pr_body
  pr_body="$(cat <<EOF
## Ralph Loop Result

Closes #${issue_number}

**Status:** ${final_status}
**Iterations:** ${iteration}

### Work Summary

${work_summary:-_No summary available._}

### Reviewer Feedback

${review_feedback:-_No feedback (shipped on first review)._}

---
_Generated by [Claude Ralph GitHub Action](https://github.com/mdelapenya/claude-ralph-github-action)_
EOF
)"

  # Check if PR already exists for this branch
  local existing_pr
  existing_pr="$(gh pr list --repo "${REPO}" --head "${branch}" --base "${base_branch}" --json url --jq '.[0].url' || echo "")"

  if [[ -n "${existing_pr}" ]]; then
    echo "Updating existing PR: ${existing_pr}"
    gh pr edit "${existing_pr}" --repo "${REPO}" \
      --title "${pr_title}" \
      --body "${pr_body}"
    echo "${existing_pr}"
  else
    echo "Creating new PR..."
    gh pr create --repo "${REPO}" \
      --head "${branch}" \
      --base "${base_branch}" \
      --title "${pr_title}" \
      --body "${pr_body}"
  fi
}

# Post a comment on the issue with the Ralph loop result.
# Args: $1 = issue number, $2 = final status, $3 = pr url
issue_comment() {
  local issue_number="$1"
  local final_status="$2"
  local pr_url="$3"

  local iteration
  iteration="$(state_read_iteration)"

  local comment
  case "${final_status}" in
    SHIPPED)
      comment="$(cat <<EOF
### Ralph Loop Complete

The task has been implemented and approved by the reviewer after **${iteration}** iteration(s).

**Pull Request:** ${pr_url}

The PR is ready for human review and merge.
EOF
)"
      ;;
    MAX_ITERATIONS)
      comment="$(cat <<EOF
### Ralph Loop - Needs Review

The Ralph loop reached the maximum of **${iteration}** iterations without the reviewer approving.

**Pull Request:** ${pr_url}

The PR contains the latest work but may need additional changes. You can:
- Review the PR and provide manual feedback
- Re-trigger the loop by removing and re-adding the label
EOF
)"
      ;;
    ERROR)
      comment="$(cat <<EOF
### Ralph Loop - Error

An error occurred during the Ralph loop on iteration **${iteration}**.

${pr_url:+**Pull Request:** ${pr_url}}

Check the action logs for details. You can re-trigger by removing and re-adding the label.
EOF
)"
      ;;
  esac

  gh issue comment "${issue_number}" --repo "${REPO}" --body "${comment}"
}
