#!/usr/bin/env bash
# pr-manager.sh - PR creation/update and issue commenting
#
# Functions for managing the pull request and issue comments
# associated with a Ralph loop run.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/state.sh"

# Create or update a pull request for the Ralph branch.
# Args: $1 = branch name, $2 = base branch, $3 = issue number,
#       $4 = issue title, $5 = final status
# Outputs: PR URL to stdout
pr_create_or_update() {
  local branch="$1"
  local base_branch="$2"
  local issue_number="$3"
  local issue_title="$4"
  local final_status="$5"

  local iteration
  iteration="$(state_read_iteration)"
  local work_summary
  work_summary="$(state_read_work_summary)"
  local review_feedback
  review_feedback="$(state_read_review_feedback)"

  # Infer conventional commit type from issue title
  local commit_type="chore"
  local lowercase_title
  lowercase_title="$(echo "${issue_title}" | tr '[:upper:]' '[:lower:]')"

  if echo "${lowercase_title}" | grep -qE '^(add|implement|create|new)'; then
    commit_type="feat"
  elif echo "${lowercase_title}" | grep -qE '^(fix|resolve|correct|repair)'; then
    commit_type="fix"
  elif echo "${lowercase_title}" | grep -qE '^(update|modify|change|improve|enhance)'; then
    commit_type="chore"
  elif echo "${lowercase_title}" | grep -qE '^(refactor|restructure|reorganize)'; then
    commit_type="refactor"
  elif echo "${lowercase_title}" | grep -qE '^(doc|document)'; then
    commit_type="docs"
  elif echo "${lowercase_title}" | grep -qE '^(test)'; then
    commit_type="test"
  fi

  # Determine status suffix based on status
  local status_suffix=""
  case "${final_status}" in
    MAX_ITERATIONS) status_suffix=" [NEEDS REVIEW]" ;;
    ERROR)        status_suffix=" [ERROR]" ;;
  esac

  local pr_title="${commit_type}: ${issue_title}${status_suffix}"

  # Build PR body
  local pr_body
  pr_body="$(cat <<EOF
## Ralph Loop Result

Closes #${issue_number}

**Status:** ${final_status}
**Iterations:** ${iteration}

### Work Summary

${work_summary:-_No summary available._}

### Reviewer Feedback

${review_feedback:-_No feedback (shipped on first review)._}

---
_Generated by [Claude Ralph GitHub Action](https://github.com/mdelapenya/claude-ralph-github-action)_
EOF
)"

  # Check if PR already exists for this branch
  local existing_pr
  existing_pr="$(gh pr list --head "${branch}" --base "${base_branch}" --json url --jq '.[0].url' 2>/dev/null || echo "")"

  if [[ -n "${existing_pr}" ]]; then
    echo "Updating existing PR: ${existing_pr}"
    gh pr edit "${existing_pr}" \
      --title "${pr_title}" \
      --body "${pr_body}"
    echo "${existing_pr}"
  else
    echo "Creating new PR..."
    gh pr create \
      --head "${branch}" \
      --base "${base_branch}" \
      --title "${pr_title}" \
      --body "${pr_body}"
  fi
}

# Post a comment on the issue with the Ralph loop result.
# Args: $1 = issue number, $2 = final status, $3 = pr url
issue_comment() {
  local issue_number="$1"
  local final_status="$2"
  local pr_url="$3"

  local iteration
  iteration="$(state_read_iteration)"

  local comment
  case "${final_status}" in
    SHIPPED)
      comment="$(cat <<EOF
### Ralph Loop Complete

The task has been implemented and approved by the reviewer after **${iteration}** iteration(s).

**Pull Request:** ${pr_url}

The PR is ready for human review and merge.
EOF
)"
      ;;
    MAX_ITERATIONS)
      comment="$(cat <<EOF
### Ralph Loop - Needs Review

The Ralph loop reached the maximum of **${iteration}** iterations without the reviewer approving.

**Pull Request:** ${pr_url}

The PR contains the latest work but may need additional changes. You can:
- Review the PR and provide manual feedback
- Re-trigger the loop by removing and re-adding the label
EOF
)"
      ;;
    ERROR)
      comment="$(cat <<EOF
### Ralph Loop - Error

An error occurred during the Ralph loop on iteration **${iteration}**.

${pr_url:+**Pull Request:** ${pr_url}}

Check the action logs for details. You can re-trigger by removing and re-adding the label.
EOF
)"
      ;;
  esac

  gh issue comment "${issue_number}" --body "${comment}"
}
